service: serverless

frameworkVersion: ">=1.1.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs6.10
  environment:
    DYNAMODB_TABLE: ${self:service}-${opt:stage, self:provider.stage}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE}"

functions:
  create:
    handler: portfolio/create.create
    events:
      - http:
          path: portfolio
          method: post
          cors: true

  list:
    handler: portfolio/list.list
    events:
      - http:
          path: portfolio
          method: get
          cors: true

  get:
    handler: portfolio/get.get
    events:
      - http:
          path: portfolio/{id}
          method: get
          cors: true

  update:
    handler: portfolio/update.update
    events:
      - http:
          path: portfolio/{id}
          method: put
          cors: true

  delete:
    handler: portfolio/delete.delete
    events:
      - http:
          path: portfolio/{id}
          method: delete
          cors: true

resources:
  Resources:
    PortfolioDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          -
            AttributeName: id
            AttributeType: S
        KeySchema:
          -
            AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:provider.environment.DYNAMODB_TABLE}
